{% set version = "4.2.0" %}

package:
  name: jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-{{ version }}.tar.gz
  sha256: e2d3601321ac74d38214e2853300ae740cd07e53d919a15862b8c71f9d840574

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jsonschema = jsonschema.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - attrs >=17.4.0
    # TODO: upstream, importlib-* are conditional to <3.8/9, but probably not worth the non-noarch builds
    - importlib-metadata
    - importlib_resources
    - pyrsistent !=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - jsonschema
  commands:
    - python -m pip check
    - jsonschema --help

about:
  home: https://github.com/Julian/jsonschema
  license: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
  description: |
    jsonschema is an implementation of JSON Schema for Python
    (supporting 2.7+ including Python 3)
  doc_url: https://python-jsonschema.readthedocs.org
  doc_source_url: https://github.com/Julian/jsonschema/blob/v{{ version }}/docs/index.rst
  dev_url: https://github.com/Julian/jsonschema

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - nehaljwani
    - bollwyvl
