{% set version = "4.1.0" %}

package:
  name: jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-{{ version }}.tar.gz
  sha256: 9dd7c33b4a96138dc37bb86b3610d3b12d30d96433d4d73435ca3025804154a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jsonschema = jsonschema.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - attrs >=17.4.0
    # TODO: upstream, this is conditional to <3.8, but probably not worth the non-noarch build
    - importlib-metadata
    - pyrsistent !=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
    # TODO: >3.2.0 sets this explicitly, but conda-forge no longer supports <3.6...
    # TODO: >3.2.0 will no longer depend on/mention these
    - six >=1.11.0
    - setuptools
    # technically still supported, but needed for noarch
    # - functools32  # [py27]

test:
  requires:
    - pip
  imports:
    - jsonschema
  commands:
    - python -m pip check
    - jsonschema --help

about:
  home: https://github.com/Julian/jsonschema
  license: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
  description: |
    jsonschema is an implementation of JSON Schema for Python
    (supporting 2.7+ including Python 3)
  doc_url: https://python-jsonschema.readthedocs.org
  doc_source_url: https://github.com/Julian/jsonschema/blob/v{{ version }}/docs/index.rst
  dev_url: https://github.com/Julian/jsonschema

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - nehaljwani
    - bollwyvl
